### ISSUE TITLE
LICENSE issue

### ISSUE THREAD

**Issue by marado** [Lopo/Lotos2#2]
Hi there,

I don't see a LICENCE file on Lotos2, even if I am assuming it is probably GPL, since you're using GPL code in it. In any case, there should be a LICENSE file in this project. 
This is all the more relevant since you've commited this change https://github.com/Lopo/Lotos2/commit/acb5845ac9db2528cbd0509f9d11ec501ca95a63#diff-e2901f6dd728e9a924f41fbbaab42a00L1 that actually removes the GPL copyright notice of that particular file.

**Comment by Lopo** [comment]
Yes, GPL is the most likely candidate. Maybe in combination with some other license. I need some time to decide. Removing copyright notice from FindMySQL.cmake is accident and should be returned in future

**Comment by Lopo** [comment]
fixed in https://github.com/Lopo/Lotos2/commit/1b295ec3fddf0b9ac069fa8c3105b41645588c0b
